---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      charset UTF-8;
      server_name  localhost;
      location / {
        root   /usr/share/nginx/html/Music/Music;
        index  index.html index.htm;
        autoindex on;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
