---
apiVersion: v1
kind: Pod
metadata:
  name: webserver-app
  labels:
    app.kubernetes.io/name: webserver-app
spec:
  volumes:
  - name: music-files
    persistentVolumeClaim:
      claimName: nfs-mini-pv-claim
  - name: nginx-conf
    configMap:
      name: nginx-conf
      items:
        - key: default.conf
          path: default.conf
  - name: log
    emptyDir: {}
  containers:
  - name: wenserver-app
    image: nginx:latest
    volumeMounts:
    - mountPath: /usr/share/nginx/html/Music
      name: music-files
    - mountPath: /etc/nginx/conf.d
      readOnly: true
      name: nginx-conf
    - mountPath: /var/log/nginx
      name: log
    ports:
    - containerPort: 80
      name: webserver-port
