---

apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.13
  selector:
    app.kubernetes.io/name: webserver-app
  ports:
  - name: webserver-endpoint
    protocol: TCP
    targetPort: webserver-port
    port: 80
