apiVersion: v1
kind: Pod
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  volumes:
  - name: jms-config
    persistentVolumeClaim:
      claimName: nfs-beast-pv-claim
  containers:
  - name: jellyfin
    image: lscr.io/linuxserver/jellyfin:arm64v8-latest
    volumeMounts:
    - mountPath: /config
      name: jms-config
    ports:
    - containerPort: 8096
      name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
spec:
  selector:
    app.kubernetes.io/name: jellyfin
  ports:
  - name: jellyfin-endpoint
    protocol: TCP
    port: 30096
    targetPort: http-web-svc
