---
#environment:
#LANG: 'C.UTF-8'

apiVersion: v1
kind: Pod
metadata:
  name: jellyfin-app
  labels:
    app.kubernetes.io/name: jellyfin-app
spec:
  nodeSelector:
    kubernetes.io/hostname: rpi4
  volumes:
  - name: jms-config
    persistentVolumeClaim:
      claimName: nfs-beast-pv-claim
  containers:
  - name: jellyfin-app
    #image: lscr.io/linuxserver/jellyfin:arm64v8-latest
    image: quay.io/linuxserver.io/jellyfin:arm64v8-latest
    volumeMounts:
    - mountPath: /config
      name: jms-config
    ports:
    - containerPort: 8096
      name: jellyfin-port

