apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-beast-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 7300Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nfs_beast/"
